from enum import Enum

class token_types(Enum):
    FROM = "FROM"
    TO = "TO"
    LINE = "LINE"
    OUT = "OUT"
    OUTPUT = "OUTPUT"
    DECLARE = "DECLARE"
    INPUT = "INPUT"
    START = "START"
    END = "END"
    INT = "INT"
    STRING = "STRING"
    VAR = "VAR"
    ADD = "ADD"
    SUB = "SUB"
    MUL = "MUL"
    GREATER = "GREATER"
    SMALLER = "SMALLER"
    EQUAL = "EQUAL"
    EQUALGREATER = "EQUALGREATER"
    EQUALSMALLER = "EQUALSMALLER"
    NOTEQUAL = "NOTEQUAL"
    DIV = "DIV"
    IF = "IF"
    FUNCTION = "FUNCTION"

class parser_states(Enum):
    SINGLE = "SINGLE"
    FUNCTION = "FUNCTION"

class node_types(Enum):
    BASE = "BASE"
    MATH = "MATH"
    VAR = "VAR"
    IF = "IF"
    ERROR = "ERROR"
    CONDITION = "CONDITION"
    FUNCTION = "FUNTION"
    INPUT = "INPUT"