from enum import Enum

class token_types(Enum):
    FROM = "FROM"
    TO = "TO"
    LINE = "LINE"
    OUT = "OUT"
    OUTPUT = "OUTPUT"
    DECLARE = "DECLARE"
    INPUT = "INPUT"
    START = "START"
    END = "END"
    INT = "INT"
    STRING = "STRING"
    VAR = "VAR"
    ADD = "ADD"
    SUB = "SUB"
    MUL = "MUL"
    GREATER = ">"
    SMALLER = "<"
    EQUAL = "=="
    EQUALGREATER = ">="
    EQUALSMALLER = "<="
    NOTEQUAL = "!="
    DIV = "DIV"
    IF = "IF"
    FUNCTION = "FUNCTION"
    ELSE = "ELSE"

class parser_states(Enum):
    SINGLE = "SINGLE"
    FUNCTION = "FUNCTION"

class node_types(Enum):
    BASE = "BASE"
    MATH = "MATH"
    VAR = "VAR"
    IF = "IF"
    ERROR = "ERROR"
    CONDITION = "CONDITION"
    FUNCTION = "FUNCTION"
    INPUT = "INPUT"
    FUNCTION_CALL = "FUNCTION_CALL"